woodnx/iQbe

.devcontainer/devcontainer.json
.github/workflows/release-please.yml

ci:  Automatic generation of release notes

---

packages/backend/prisma/migrations/20240810141917_add_culumn_permission_to_users/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/src/applications/usecases/AuthUseCase.ts
packages/backend/src/db/types.ts
packages/backend/src/domains/User/index.ts
packages/backend/src/interfaces/infra/UserInfra.ts

- Add column `permission` to `users` table
- Add property `permission` to `User` domain

feat: Add permission to user

---

.devcontainer/devcontainer.json
CHANGELOG.md
package-lock.json
package.json
packages/api/openapi.yaml
packages/backend/prisma/migrations/20240810141917_add_culumn_permission_to_users/migration.sql
packages/backend/prisma/migrations/20240816095722_create_table_tags/migration.sql
packages/backend/prisma/migrations/20240816111553_create_table_tagging/migration.sql
packages/backend/prisma/migrations/20240816120845_add_columns_registered_created_to_tagging_tags/migration.sql
packages/backend/prisma/migrations/20240817151507_add_columns_to_tags_modified_creator_id/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/src/applications/usecases/AuthUseCase.ts
packages/backend/src/db/types.ts
packages/backend/src/domains/Tag/ITagRepository.ts
packages/backend/src/domains/Tag/TagService.ts
packages/backend/src/domains/Tag/index.ts
packages/backend/src/domains/User/index.ts
packages/backend/src/interfaces/controllers/TagController.ts
packages/backend/src/interfaces/infra/TagInfra.ts
packages/backend/src/interfaces/infra/UserInfra.ts
packages/backend/src/routes/tags.ts

Implemented tag addition / editing / fetching / deleting features

feat(backend): Add tag feature

---

.devcontainer/devcontainer.json
CHANGELOG.md
package-lock.json
package.json
packages/api/openapi.yaml
packages/backend/prisma/migrations/20240810141917_add_culumn_permission_to_users/migration.sql
packages/backend/prisma/migrations/20240816095722_create_table_tags/migration.sql
packages/backend/prisma/migrations/20240816111553_create_table_tagging/migration.sql
packages/backend/prisma/migrations/20240816120845_add_columns_registered_created_to_tagging_tags/migration.sql
packages/backend/prisma/migrations/20240817151507_add_columns_to_tags_modified_creator_id/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/src/applications/usecases/AuthUseCase.ts
packages/backend/src/db/types.ts
packages/backend/src/domains/Tag/ITagRepository.ts
packages/backend/src/domains/Tag/TagService.ts
packages/backend/src/domains/Tag/index.ts
packages/backend/src/domains/User/index.ts
packages/backend/src/interfaces/controllers/TagController.ts
packages/backend/src/interfaces/infra/TagInfra.ts
packages/backend/src/interfaces/infra/UserInfra.ts
packages/backend/src/routes/tags.ts

Implemented tag addition / editing / fetching / deleting features

feat(backend): Add tag feature (#79)

---

packages/api/openapi.yaml
packages/backend/src/domains/Quiz/IQuizRepository.ts
packages/backend/src/interfaces/controllers/QuizController.ts
packages/backend/src/interfaces/infra/QuizInfra.ts
packages/backend/src/routes/quizzes.ts
packages/frontend/src/components/CsvEditor.tsx
packages/frontend/src/components/CsvFileImporter.tsx

- route`/quizzes/multiple` を追加
- 上記routeの追加に伴い，CSVインポートの際のAPI呼び出しを変更
Fixes #90

feat: Add ability to add multiple quizzes

---

packages/frontend/src/components/PracticeSceneChanger.tsx
packages/frontend/src/pages/practice.tsx

fix(frontend): problems that start automatically in practice

---

packages/frontend/src/components/CategorySelector.tsx
packages/frontend/src/components/QuizDetailesMenu.tsx
packages/frontend/src/components/QuizEditForm.tsx
packages/frontend/src/components/QuizEditModal.tsx
packages/frontend/src/components/WorkbookCreateAndSelector.tsx
packages/frontend/src/components/WorkbookCreateModalButton.tsx
packages/frontend/src/components/WorkbookSelector.tsx

feat(frontend): `QuizEditModal`にクイズ編集機能を追加

---

packages/api/openapi.yaml
packages/backend/src/routes/analysis.ts
packages/frontend/src/components/ActivityUserRanking.tsx

`nickname`がない場合に表示されなくなっていたため，`nickname`が`null`の場合に`username`を表示するように変更
それにあわせてAPI仕様も変更

fix: ランキングでユーザ名が表示されない問題を修正

---

CHANGELOG.md
package-lock.json
package.json

Revert "chore(main): release 3.4.0"

---

packages/api/openapi.yaml
packages/backend/src/interfaces/controllers/QuizController.ts
packages/backend/src/routes/analysis.ts
packages/frontend/src/components/ActivityUserRanking.tsx
packages/frontend/src/components/CategorySelector.tsx
packages/frontend/src/components/QuizDetailesMenu.tsx
packages/frontend/src/components/QuizEditForm.tsx
packages/frontend/src/components/QuizEditModal.tsx
packages/frontend/src/components/WorkbookCreateAndSelector.tsx
packages/frontend/src/components/WorkbookCreateModalButton.tsx
packages/frontend/src/components/WorkbookSelector.tsx

Revert "Revert "v3.5.0""

---

package-lock.json
packages/api/openapi.yaml
packages/backend/prisma/migrations/20240922053350_create_new_table_profile/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/src/applications/usecases/AuthUseCase.ts
packages/backend/src/db/types.ts
packages/backend/src/domains/ProfileImage/IProfileImageRepository.ts
packages/backend/src/domains/ProfileImage/index.ts
packages/backend/src/domains/User/index.ts
packages/backend/src/index.ts
packages/backend/src/interfaces/controllers/IController.ts
packages/backend/src/interfaces/infra/ProfileImageInfra.ts
packages/backend/src/interfaces/infra/UserInfra.ts
packages/backend/src/routes/csv.ts
packages/backend/src/routes/i.ts
packages/frontend/package.json
packages/frontend/src/components/ButtonWithFileInput.tsx
packages/frontend/src/components/ImageCropper.tsx
packages/frontend/src/components/SettingProfile.tsx
packages/frontend/src/components/UserInfo.tsx
packages/frontend/src/components/styles/ImageCropper.module.css
packages/frontend/src/utils/getCroppedImage.ts
scripts/dev.mjs

feat: プロフィール画像の編集

---

CHANGELOG.md
package-lock.json
package.json
packages/backend/src/applications/usecases/AuthUseCase.ts
packages/frontend/src/components/SettingProfile.tsx
packages/frontend/src/components/UserSignupModal.tsx
packages/frontend/src/components/UsernameInput.tsx

feat: usernameを入力するときにdebounceを設ける

---

packages/api/openapi.yaml
packages/backend/prisma/migrations/20241015102543_add_new_column_description_to_tags/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/src/db/types.ts
packages/backend/src/domains/Tag/index.ts
packages/backend/src/interfaces/controllers/TagController.ts
packages/backend/src/interfaces/infra/TagInfra.ts
packages/frontend/src/components/ButtonWithFileInput.tsx
packages/frontend/src/components/SettingAccount.tsx
packages/frontend/src/components/SettingProfile.tsx
packages/frontend/src/components/TagBadge.tsx
packages/frontend/src/components/TagCard.tsx
packages/frontend/src/components/TagCreateButton.tsx
packages/frontend/src/components/TagCreateCard.tsx
packages/frontend/src/components/TagEditForm.tsx
packages/frontend/src/components/TagSetting.tsx
packages/frontend/src/pages/setting.tsx
packages/frontend/src/utils/rgb.ts
packages/frontend/src/utils/tagColorSwatches.ts

feat: タグの編集・追加・削除のフロントエンド実装 

---

packages/api/openapi.yaml
packages/backend/src/applications/queryservices/IQuizQueryService.ts
packages/backend/src/applications/usecases/QuizUseCase.ts
packages/backend/src/interfaces/controllers/QuizController.ts
packages/backend/src/interfaces/infra/QuizInfra.ts
packages/backend/src/routes/like.ts
packages/backend/src/routes/practice.ts
packages/backend/src/routes/quizzes.ts
packages/backend/src/routes/register.ts
packages/backend/src/routes/unlike.ts
packages/backend/src/routes/unregister.ts
packages/backend/src/routes/workbooks.ts
packages/frontend/src/components/FilteringWorkbook.tsx
packages/frontend/src/components/PracticeSceneChanger.tsx
packages/frontend/src/components/QuizViewer.tsx
packages/frontend/src/hooks/useQuizSize.ts
packages/frontend/src/pages/practice.tsx

refactor: `/quizzes/size` パスの作成  

---

packages/backend/src/applications/usecases/CategoryUseCase.ts
packages/backend/src/domains/Category/CategoryRepository.ts
packages/backend/src/domains/Category/index.ts
packages/backend/src/domains/SubCategory/SubCategoryRepository.ts
packages/backend/src/domains/SubCategory/index.ts
packages/backend/src/interfaces/controllers/CategoryController.ts
packages/backend/src/interfaces/infra/CategoryInfra.ts
packages/backend/src/interfaces/infra/SubCategoryInfra.ts
packages/backend/src/routes/categories.ts
packages/frontend/src/App.tsx
packages/frontend/src/components/CategoryBaseCard.tsx
packages/frontend/src/components/CategoryCard.tsx
packages/frontend/src/components/CategoryCreateModal.tsx
packages/frontend/src/components/CategoryCreateModalButton.tsx
packages/frontend/src/components/CategoryEditForm.tsx
packages/frontend/src/components/CategoryEditModal.tsx
packages/frontend/src/components/CategorySetting.tsx
packages/frontend/src/components/CategorySubCard.tsx
packages/frontend/src/components/SettingServer.tsx

feat: ジャンル編集機能

---

package-lock.json
packages/backend/package.json
packages/frontend/package.json
packages/frontend/src/components/CreateDashboard.tsx
packages/frontend/src/components/CreateWorkbookModal.tsx
packages/frontend/src/components/QuizEditForm.tsx
packages/frontend/src/components/QuizEditModal.tsx
packages/frontend/src/components/QuizFavoriteButton.tsx
packages/frontend/src/components/QuizMylistButton.tsx

fix: npm run build でエラーが吐かれる問題  1

---

packages/frontend/src/App.tsx
packages/frontend/src/components/MylistCreateModal.tsx
packages/frontend/src/components/MylistEditForm.tsx
packages/frontend/src/components/MylistEditModal.tsx
packages/frontend/src/components/MylistEditModalButton.tsx
packages/frontend/src/components/QuizMylistButton.tsx
packages/frontend/src/pages/mylists.tsx

Restructured MylistCreateModal to be unique per QuizList, enhancing performance. Updated related components and modal handling to reflect this change.
Fixes #2

refactor(frontend): Refactor MylistCreateModal structure for performance optimization

---

packages/api/openapi.yaml
packages/backend/src/interfaces/controllers/QuizController.ts
packages/backend/src/interfaces/infra/QuizInfra.ts
packages/backend/src/routes/analysis.ts
packages/backend/src/routes/i.ts
packages/frontend/src/hooks/useQuizSize.ts
packages/frontend/src/hooks/useQuizzes.ts

fix: 正しく絞り込みできない問題を修正

---

packages/frontend/src/hooks/useQuizSize.ts
packages/frontend/src/hooks/useQuizzes.ts

fix: workbookによる絞り込みができない 

---

.devcontainer/docker-compose.yml
packages/api/openapi.yaml
packages/backend/prisma/migrations/20241214061543_delete_nullable_mid/migration.sql
packages/backend/prisma/schema.prisma
packages/backend/src/applications/usecases/QuizUseCase.ts
packages/backend/src/db/types.ts
packages/backend/src/interfaces/controllers/MylistController.ts
packages/backend/src/interfaces/controllers/TagController.ts
packages/backend/src/interfaces/controllers/WorkbookController.ts
packages/backend/src/interfaces/infra/QuizInfra.ts
packages/backend/src/routes/like.ts
packages/backend/src/routes/practice.ts
packages/backend/src/routes/quizzes.ts
packages/backend/src/routes/register.ts
packages/backend/src/routes/unlike.ts
packages/backend/src/routes/unregister.ts
packages/frontend/src/components/CategorySelector.tsx
packages/frontend/src/components/CategorySelectorBase.tsx
packages/frontend/src/components/PracticeQuizInfo.tsx
packages/frontend/src/components/PracticeSceneChanger.tsx
packages/frontend/src/components/QuizCard.tsx
packages/frontend/src/components/QuizDetailesMenu.tsx
packages/frontend/src/components/QuizEditForm.tsx
packages/frontend/src/components/QuizEditModal.tsx
packages/frontend/src/components/QuizList.tsx
packages/frontend/src/components/QuizMylistButton.tsx
packages/frontend/src/components/QuizWorkbookBadge.tsx

refactor!: APIのレスポンスを変更

---

packages/backend/src/interfaces/controllers/CategoryController.ts
packages/backend/src/interfaces/controllers/InviteCodeController.ts
packages/backend/src/interfaces/controllers/TagController.ts
packages/backend/src/middleware/verifyAuthToken.ts
packages/backend/src/types/global.ts

feat(backend): APIの権限による制限をしっかりする 

---

packages/frontend/src/App.tsx
packages/frontend/src/components/CategorySelector.tsx
packages/frontend/src/components/CategorySelectorBase.tsx
packages/frontend/src/components/QuizCard.tsx
packages/frontend/src/components/QuizDetailesMenu.tsx
packages/frontend/src/components/QuizDetailesModal.tsx
packages/frontend/src/components/QuizEditForm.tsx
packages/frontend/src/components/TagInput.tsx
packages/frontend/src/components/WorkbookCreateAndSelector.tsx

feat(frontend): クイズの詳細を表示

---

package-lock.json
packages/backend/package.json
packages/backend/src/index.ts

feat(backend): validatorの導入

---

.gitignore
packages/backend/src/index.ts
packages/backend/src/routes/i.ts

fix: build時に画像が失われる問題を修正

---

packages/frontend/index.html

fix(frontend): iOSでのinputのフォーカス時に勝手にズームインされる

---

packages/frontend/index.html
packages/frontend/src/main.tsx

chore(frontend): フォントの変更

---

packages/frontend/src/components/WorkbookShowQuizList.tsx
packages/frontend/src/hooks/useAuth.ts
packages/frontend/src/layouts/index.tsx
packages/frontend/src/pages/mylists.tsx

fix(frontend): Routerのアクセス制限をつける

---

packages/frontend/src/App.tsx
packages/frontend/src/components/MylistEditModalButton.tsx
packages/frontend/src/components/WorkbookCard.tsx
packages/frontend/src/components/WorkbookCreateForm.tsx
packages/frontend/src/components/WorkbookCreateModalButton.tsx
packages/frontend/src/components/WorkbookDeleteModal.tsx
packages/frontend/src/components/WorkbookEditModal.tsx
packages/frontend/src/components/WorkbookSearch.tsx
packages/frontend/src/components/WorkbookShowQuizList.tsx

feat(frontend): 問題集の編集機能 

---

.gitignore
Dockerfile
compose_example.yml
package-lock.json
package.json
packages/api/package.json
packages/frontend/package.json
packages/frontend/src/components/PracticeQuizInfo.tsx
packages/frontend/src/components/QuizCard.tsx

fix: build with docker

---

.config/docker-example.env
.devcontainer/docker-compose.yml
.devcontainer/init.sh
compose_example.yml
packages/backend/src/database.ts

fix: Not working `/welcome` page

---

packages/frontend/src/utils/client.ts

fix: throws CORS error when production.

---

packages/backend/src/interfaces/infra/QuizInfra.ts

chore: 必要ない処理を削除

---

packages/frontend/src/components/PracticeQuizButton.tsx
packages/frontend/src/components/PracticeQuizController.tsx
packages/frontend/src/components/PracticeSceneChanger.tsx
packages/frontend/src/components/PracticeTypewriteQuiz.tsx
packages/frontend/src/hooks/useTypewriter.ts
packages/frontend/src/pages/practice.tsx

fix(frontend): improved performance of `practice`

---

packages/frontend/src/components/PracticeQuizController.tsx

fix(frontend): an issue where the skip button could not be pressed after pressing the button and skipping
